import 'package:hive_flutter/hive_flutter.dart';
import '../model/user_model.dart';
import '../model/checkin_model.dart';
import '../model/emergency_contact_model.dart';
import '../model/settings_model.dart';
import '../../core/constants/app_constants.dart';

class HiveService {
  static final HiveService _instance = HiveService._internal();
  factory HiveService() => _instance;
  HiveService._internal();

  // Boxes
  Box<UserModel>? _userBox;
  Box<CheckInModel>? _checkinBox;
  Box<EmergencyContactModel>? _contactBox;
  Box<SettingsModel>? _settingsBox;

  /// Initialize Hive and register adapters
  Future<void> init() async {
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    // Hive.registerAdapter(UserModelAdapter());
    // Hive.registerAdapter(CheckInModelAdapter());
    // Hive.registerAdapter(EmergencyContactModelAdapter());
    // Hive.registerAdapter(SettingsModelAdapter());

    // Open boxes
    _userBox = await Hive.openBox<UserModel>(AppConstants.userBoxName);
    _checkinBox = await Hive.openBox<CheckInModel>(AppConstants.checkinBoxName);
    _contactBox = await Hive.openBox<EmergencyContactModel>(
      AppConstants.contactsBoxName,
    );
    _settingsBox = await Hive.openBox<SettingsModel>(
      AppConstants.settingsBoxName,
    );
  }

  // ==================== User Operations ====================
  
  Future<void> saveUser(UserModel user) async {
    await _userBox?.put('current_user', user);
  }

  UserModel? getCurrentUser() {
    return _userBox?.get('current_user');
  }

  Future<void> deleteUser() async {
    await _userBox?.delete('current_user');
  }

  Future<void> updateUser(UserModel user) async {
    await saveUser(user);
  }

  // ==================== Check-in Operations ====================
  
  Future<void> saveCheckIn(CheckInModel checkIn) async {
    await _checkinBox?.put(checkIn.id, checkIn);
  }

  List<CheckInModel> getAllCheckIns() {
    return _checkinBox?.values.toList() ?? [];
  }

  List<CheckInModel> getRecentCheckIns({int limit = 10}) {
    final all = getAllCheckIns();
    all.sort((a, b) => b.timestamp.compareTo(a.timestamp));
    return all.take(limit).toList();
  }

  CheckInModel? getLastCheckIn() {
    final recent = getRecentCheckIns(limit: 1);
    return recent.isNotEmpty ? recent.first : null;
  }

  Future<void> deleteCheckIn(String id) async {
    await _checkinBox?.delete(id);
  }

  List<CheckInModel> getPendingSyncCheckIns() {
    return _checkinBox?.values.where((c) => !c.isSynced).toList() ?? [];
  }

  Future<void> markCheckInAsSynced(String id) async {
    final checkIn = _checkinBox?.get(id);
    if (checkIn != null) {
      await _checkinBox?.put(
        id,
        checkIn.copyWith(isSynced: true),
      );
    }
  }

  // ==================== Emergency Contact Operations ====================
  
  Future<void> saveContact(EmergencyContactModel contact) async {
    await _contactBox?.put(contact.id, contact);
  }

  List<EmergencyContactModel> getAllContacts() {
    final contacts = _contactBox?.values.toList() ?? [];
    contacts.sort((a, b) => a.priority.compareTo(b.priority));
    return contacts;
  }

  EmergencyContactModel? getContact(String id) {
    return _contactBox?.get(id);
  }

  Future<void> updateContact(EmergencyContactModel contact) async {
    await saveContact(contact);
  }

  Future<void> deleteContact(String id) async {
    await _contactBox?.delete(id);
  }

  int getContactCount() {
    return _contactBox?.length ?? 0;
  }

  // ==================== Settings Operations ====================
  
  Future<void> saveSettings(SettingsModel settings) async {
    await _settingsBox?.put('settings', settings);
  }

  SettingsModel getSettings() {
    return _settingsBox?.get('settings') ?? const SettingsModel();
  }

  Future<void> updateSettings(SettingsModel settings) async {
    await saveSettings(settings.copyWith(updatedAt: DateTime.now()));
  }

  // ==================== Clear All Data ====================
  
  Future<void> clearAllData() async {
    await _userBox?.clear();
    await _checkinBox?.clear();
    await _contactBox?.clear();
    await _settingsBox?.clear();
  }

  Future<void> close() async {
    await _userBox?.close();
    await _checkinBox?.close();
    await _contactBox?.close();
    await _settingsBox?.close();
  }
}