// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUhQHuz8BD5fomzGS7QEL7iYYNyjmfpDE',
    appId: '1:356949727125:web:164c114f07b7a17dd5889c',
    messagingSenderId: '356949727125',
    projectId: 'are-you-okay-bd',
    authDomain: 'are-you-okay-bd.firebaseapp.com',
    storageBucket: 'are-you-okay-bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUhQHuz8BD5fomzGS7QEL7iYYNyjmfpDE',
    appId: '1:356949727125:android:164c114f07b7a17dd5889c',
    messagingSenderId: '356949727125',
    projectId: 'are-you-okay-bd',
    storageBucket: 'are-you-okay-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUhQHuz8BD5fomzGS7QEL7iYYNyjmfpDE',
    appId: '1:356949727125:ios:164c114f07b7a17dd5889c',
    messagingSenderId: '356949727125',
    projectId: 'are-you-okay-bd',
    storageBucket: 'are-you-okay-bd.firebasestorage.app',
    iosBundleId: 'com.areyouokay.app',
  );
}
